### PR TITLE
Update version to 101.1.2

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by ivankravets** [comment]
Please make a path/fix release with `101.1.3`? Thanks!

**Comment by LowPowerLab** [comment]
Done, thank you.

**Comment by ivankravets** [comment]
Please remove 101.1.3 tag, update library.*** manifests "version"=101.1.1. New commit, then tag. Thanks!

**Comment by LowPowerLab** [comment]
Whoops forgot to update the files, sorry about that.
So I deleted the old tag, updated the .json and .properties files with 101.1.3 and made a new tag.
Hopefully all is good now.

**Comment by ivankravets** [comment]
Yes, now everything looks great! Thanks!

**Pull request merged**
